ui.button.click=random/click
block.grass.break=dig/grass1,dig/grass2,dig/grass3,dig/grass4
block.grass.place=dig/grass1,dig/grass2,dig/grass3,dig/grass4
block.grass.step=step/grass1,step/grass2,step/grass3,step/grass4,step/grass5,step/grass6
block.gravel.break=dig/gravel1,dig/gravel2,dig/gravel3,dig/gravel4
block.gravel.place=dig/gravel1,dig/gravel2,dig/gravel3,dig/gravel4
block.gravel.step=step/gravel1,step/gravel2,step/gravel3,step/gravel4
block.stone.break=dig/stone1,dig/stone2,dig/stone3,dig/stone4
block.stone.place=dig/stone1,dig/stone2,dig/stone3,dig/stone4
block.stone.step=step/stone1,step/stone2,step/stone3,step/stone4,step/stone5,step/stone6
block.wood.break=dig/wood1,dig/wood2,dig/wood3,dig/wood4
block.wood.place=dig/wood1,dig/wood2,dig/wood3,dig/wood4
block.wood.step=step/wood1,step/wood2,step/wood3,step/wood4,step/wood5,step/wood6
block.sand.break=dig/sand1,dig/sand2,dig/sand3,dig/sand4
block.sand.place=dig/sand1,dig/sand2,dig/sand3,dig/sand4
block.sand.step=step/sand1,step/sand2,step/sand3,step/sand4,step/sand5
entity.generic.eat=random/eat1,random/eat2,random/eat3
entity.player.burp=random/burp
entity.player.hurt=damage/hit1,damage/hit2,damage/hit3
entity.player.attack.weak=entity/player/attack/weak1@0.7,entity/player/attack/weak2@0.7,entity/player/attack/weak3@0.7,entity/player/attack/weak4@0.7
entity.player.attack.strong=entity/player/attack/strong1@0.6,entity/player/attack/strong2@0.6,entity/player/attack/strong3@0.6,entity/player/attack/strong4@0.6,entity/player/attack/strong5@0.7,entity/player/attack/strong6@0.7
entity.player.attack.knockback=entity/player/attack/knockback1@0.7,entity/player/attack/knockback2@0.7,entity/player/attack/knockback3@0.7,entity/player/attack/knockback4@0.7
entity.player.attack.crit=entity/player/attack/crit1@0.7,entity/player/attack/crit2@0.7,entity/player/attack/crit3@0.7
entity.player.attack.sweep=entity/player/attack/sweep1@0.7,entity/player/attack/sweep2@0.7,entity/player/attack/sweep3@0.7,entity/player/attack/sweep4@0.7,entity/player/attack/sweep5@0.7,entity/player/attack/sweep6@0.7,entity/player/attack/sweep7@0.7
entity.player.attack.nodamage=entity/player/attack/weak1@0.7,entity/player/attack/weak2@0.7,entity/player/attack/weak3@0.7,entity/player/attack/weak4@0.7
entity.cow.hurt=mob/cow/hurt1,mob/cow/hurt2,mob/cow/hurt3
entity.pig.hurt=mob/pig/say1,mob/pig/say2,mob/pig/say3
entity.sheep.hurt=mob/sheep/say1,mob/sheep/say2,mob/sheep/say3
entity.experience_orb.pickup=random/orb
entity.player.levelup=random/levelup
entity.item.pickup=random/pop
block.wooden_door.open=block/wooden_door/open,block/wooden_door/open2,block/wooden_door/open3,block/wooden_door/open4
block.wooden_door.close=block/wooden_door/close,block/wooden_door/close2,block/wooden_door/close3,block/wooden_door/close4
entity.player.splash=liquid/splash,liquid/splash2
block.chest.open=block/chest/open
block.chest.close=block/chest/close,block/chest/close2,block/chest/close3
entity.villager.hurt=mob/villager/hit1,mob/villager/hit2,mob/villager/hit3,mob/villager/hit4
entity.villager.yes=mob/villager/yes1,mob/villager/yes2,mob/villager/yes3
entity.villager.no=mob/villager/no1,mob/villager/no2,mob/villager/no3
